### ISSUE TITLE
Suggestion : Probably You liked it 

### ISSUE THREAD

**Issue by ghost** [jaswanthsinghrasaputra/git-practice#1]
The Following Should be better.! 
```css
.animated-button {
    display: inline-block;
    padding: 12px 30px;
    font-size: 16px;
    border: none;
    background-color: #3498db;
    color: #ffffff;
    border-radius: 5px;
    cursor: pointer;
    position: relative;
    overflow: hidden;
    transition: background-color 0.3s ease;
}

.animated-button::before {
    content: "";
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 0;
    height: 100%;
    background-color: rgba(255, 255, 255, 0.1);
    opacity: 0;
    transition: opacity 0.3s ease, width 0.3s ease;
}

.animated-button:hover {
    background-color: #2980b9;
}

.animated-button:hover::before {
    width: 100%;
    opacity: 1;
}

```
